/********************************************************************
* TFragmentFromNTupleDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFragmentFromNTupleDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFragmentFromNTupleDictionary();
extern void G__cpp_setup_inheritanceTFragmentFromNTupleDictionary();
extern void G__cpp_setup_typetableTFragmentFromNTupleDictionary();
extern void G__cpp_setup_memvarTFragmentFromNTupleDictionary();
extern void G__cpp_setup_globalTFragmentFromNTupleDictionary();
extern void G__cpp_setup_memfuncTFragmentFromNTupleDictionary();
extern void G__cpp_setup_funcTFragmentFromNTupleDictionary();
extern void G__set_cpp_environmentTFragmentFromNTupleDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Griffin.hh"
#include "TFragment.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TClass;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TBuffer;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TObject;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TVector3;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_Detector;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_TFragment;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator;
extern G__linked_taginfo G__TFragmentFromNTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Detector,allocator<Detector> > G__vectorlEDetectorcOallocatorlEDetectorgRsPgR;
